const mongoose = require('mongoose');

const cummStateSchema = new mongoose.Schema({
  date: { type: Date, default: Date.now },
  createdAt: { type: Date, default: Date.now },
  'Abuja FCT': { type: Number, default: 0 },
  Abia: { type: Number, default: 0 },
  Adamawa: { type: Number, default: 0 },
  'Akwa Ibom': { type: Number, default: 0 },
  Anambra: { type: Number, default: 0 },
  Bauchi: { type: Number, default: 0 },
  Bayelsa: { type: Number, default: 0 },
  Benue: { type: Number, default: 0 },
  Borno: { type: Number, default: 0 },
  'Cross River': { type: Number, default: 0 },
  Delta: { type: Number, default: 0 },
  Ebonyi: { type: Number, default: 0 },
  Edo: { type: Number, default: 0 },
  Ekiti: { type: Number, default: 0 },
  Enugu: { type: Number, default: 0 },
  Gombe: { type: Number, default: 0 },
  Imo: { type: Number, default: 0 },
  Jigawa: { type: Number, default: 0 },
  Kaduna: { type: Number, default: 0 },
  Kano: { type: Number, default: 0 },
  Katsina: { type: Number, default: 0 },
  Kebbi: { type: Number, default: 0 },
  Kogi: { type: Number, default: 0 },
  Kwara: { type: Number, default: 0 },
  Lagos: { type: Number, default: 0 },
  Nassarawa: { type: Number, default: 0 },
  Niger: { type: Number, default: 0 },
  Ogun: { type: Number, default: 0 },
  Ondo: { type: Number, default: 0 },
  Osun: { type: Number, default: 0 },
  Oyo: { type: Number, default: 0 },
  Plateau: { type: Number, default: 0 },
  Rivers: { type: Number, default: 0 },
  Sokoto: { type: Number, default: 0 },
  Taraba: { type: Number, default: 0 },
  Yobe: { type: Number, default: 0 },
  Zamfara: { type: Number, default: 0 },

});

module.exports = mongoose.model('CummState', cummStateSchema);
